# Generated by Django 5.1.7 on 2025-05-04 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_position_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrate',
            name='hours_per_day',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='payrate',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee'),
        ),
        migrations.AlterField(
            model_name='payrate',
            name='pay_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
