# Generated by Django 5.1.7 on 2025-05-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_payrate_hours_per_day_alter_payrate_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deductions',
            name='label',
            field=models.CharField(default='Other', max_length=100),
        ),
    ]
